version: "3.2"
services:
  web:
    build: webapp
    links:
      - db:db
    volumes:
      - "/volumes/config:/app/timeoff-management/config"
    ports:
      - "8189:3000"
    environment: 
      - ALLOW_ACCOUNTS_CREATION=true 
      - NODE_ENV=production
      - MYSQL_HOST=db
      - MYSQL_USER=timeoff
      - MYSQL_DATABASE=timeoff
      - MYSQL_PASSWORD=timeoff
  db: 
    image: mariadb:10.3
    restart: unless-stopped
    volumes: 
      - "/volumes/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=timeoff
      - MYSQL_DATABASE=timeoff
      - MYSQL_USER=timeoff
      - MYSQL_PASSWORD=timeoff
